<a href="https://colab.research.google.com/github/JaiSuryaPrabu/deep_learning/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch 
## Link
https://www.learnpytorch.io/

# 1. Pytorch fundamentals

In [ ]:
# importing torch and checking its version
import torch
torch.__version__

'2.0.1+cu118'

## Tensor

In [ ]:
# 0 dimensinal tensor - Scalar
scalar = torch.tensor(10)
print(scalar)

# dimensions
print("The number of dimensions in the scalar : ",scalar.ndim)

# from tensor.Torch to int data type
# item() is only for scalar
print(scalar.item())

tensor(10)
The number of dimensions in the scalar :  0
10


In [ ]:
# 1D tensor - vector
vector = torch.tensor([10,10])
print(vector)

# dimensions
print("The number of dimensions in the vector : ",vector.ndim)

# shape
print("The shape of the vector : ",vector.shape)

tensor([10, 10])
The number of dimensions in the vector :  1
The shape of the vector :  torch.Size([2])


In [ ]:
# Matrix 
matrix = torch.tensor(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)
print(matrix)

# dimensions
print("The dimensions in the matrix : ",matrix.ndim)

# shape 
print("The shape of the matrix : ",matrix.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
The dimensions in the matrix :  2
The shape of the matrix :  torch.Size([3, 3])


In [ ]:
# Tensors
tensors = torch.tensor(
    [[[1,2,3],
      [4,5,6],
      [7,8,9]]]
)

print(tensors,tensors.shape,tensors.ndim)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3]) 3


## Random Tensors

In [15]:
# torch.rand() gives random tensors
# arguments : 
#   size = (rows , columns)

random_tensor = torch.rand(size = (3,3))
print(random_tensor)

# to know about the data type
print(random_tensor.dtype)

tensor([[0.2370, 0.6287, 0.5065],
        [0.2682, 0.3741, 0.6927],
        [0.7619, 0.2704, 0.7009]])
torch.float32


In [16]:
# tensors of zeros
zero_tensors = torch.zeros(size = (3,3))
print(zero_tensors)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [17]:
# tensors of ones
one_tensors = torch.ones(size=(3,3))
one_tensors

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## Range of tensors

In [19]:
# arange(start , end , step)
range_tensor = torch.arange(start=0,end=10,step=1)
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# copying the shape of another tensor

# zeros_like(input)
zero_copied = torch.zeros_like(range_tensor)
print(zero_copied)

# ones_like(input)
ones_copied = torch.ones_like(zero_tensors)
print(ones_copied)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## Tensor Datatype

* Float
    * 32 bit
    * 64 bit
    * 16 bit
* Complex
    * 32 bit
    * 64 bit
    * 128 bit
* Integer
    * 8 bit
        * signed
        * unsigned
    * 16 bit
        * signed
    * 32 bit
        * signed
    * 64 bit
        * signed
    * Quantized
        * 4 bit
            * unsigned 
        * 8 bit
            * signed
            * unsigned
        * 32 bit
            * signed
* Boolean

In [22]:
# float default values
float_tensor = torch.tensor([0.1,0.2,0.3],
                            dtype = None,
                            device = None,
                            requires_grad = False)

float_tensor.dtype,float_tensor.device

(torch.float32, device(type='cpu'))