<a href="https://colab.research.google.com/github/JaiSuryaPrabu/deep_learning/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch 
## Resource Link
https://www.learnpytorch.io/

# 1. Pytorch fundamentals

In [2]:
# importing torch and checking its version
import torch
torch.__version__

'2.0.1+cu118'

## Tensor

In [3]:
# 0 dimensinal tensor - Scalar
scalar = torch.tensor(10)
print(scalar)

# dimensions
print("The number of dimensions in the scalar : ",scalar.ndim)

# from tensor.Torch to int data type
# item() is only for scalar
print(scalar.item())

tensor(10)
The number of dimensions in the scalar :  0
10


In [4]:
# 1D tensor - vector
vector = torch.tensor([10,10])
print(vector)

# dimensions
print("The number of dimensions in the vector : ",vector.ndim)

# shape
print("The shape of the vector : ",vector.shape)

tensor([10, 10])
The number of dimensions in the vector :  1
The shape of the vector :  torch.Size([2])


In [5]:
# Matrix 
matrix = torch.tensor(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)
print(matrix)

# dimensions
print("The dimensions in the matrix : ",matrix.ndim)

# shape 
print("The shape of the matrix : ",matrix.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
The dimensions in the matrix :  2
The shape of the matrix :  torch.Size([3, 3])


In [6]:
# Tensors
tensors = torch.tensor(
    [[[1,2,3],
      [4,5,6],
      [7,8,9]]]
)

print(tensors,tensors.shape,tensors.ndim)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3]) 3


## Random Tensors

In [7]:
# torch.rand() gives random tensors
# arguments : 
#   size = (rows , columns)

random_tensor = torch.rand(size = (3,3))
print(random_tensor)

# to know about the data type
print(random_tensor.dtype)

tensor([[0.8890, 0.3524, 0.3225],
        [0.5395, 0.5693, 0.5614],
        [0.7932, 0.6283, 0.6758]])
torch.float32


In [8]:
# tensors of zeros
zero_tensors = torch.zeros(size = (3,3))
print(zero_tensors)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# tensors of ones
one_tensors = torch.ones(size=(3,3))
one_tensors

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## Range of tensors

In [10]:
# arange(start , end , step)
range_tensor = torch.arange(start=0,end=10,step=1)
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# copying the shape of another tensor

# zeros_like(input)
zero_copied = torch.zeros_like(range_tensor)
print(zero_copied)

# ones_like(input)
ones_copied = torch.ones_like(zero_tensors)
print(ones_copied)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## Tensor Datatype

* Float
    * 32 bit
    * 64 bit
    * 16 bit
* Complex
    * 32 bit
    * 64 bit
    * 128 bit
* Integer
    * 8 bit
        * signed
        * unsigned
    * 16 bit
        * signed
    * 32 bit
        * signed
    * 64 bit
        * signed
    * Quantized
        * 4 bit
            * unsigned 
        * 8 bit
            * signed
            * unsigned
        * 32 bit
            * signed
* Boolean

In [12]:
# float default values
float_tensor = torch.tensor([0.1,0.2,0.3],
                            dtype = None,
                            device = None,
                            requires_grad = False)

float_tensor.dtype,float_tensor.device

(torch.float32, device(type='cpu'))

## Information from tensors

In [13]:
# the main informations are
#   1. Shape
#   2. Data type
#   3. Device
info_tensor = torch.rand(size=(3,3))
print("The tensor : ",info_tensor)
print("\nThe Data type of the tensor : ",info_tensor.dtype)
print("\nThe Device of the tensor : ",info_tensor.device)

The tensor :  tensor([[0.8771, 0.3615, 0.9222],
        [0.4467, 0.3304, 0.2865],
        [0.9943, 0.6444, 0.3749]])

The Data type of the tensor :  torch.float32

The Device of the tensor :  cpu


## Tensor Operations
* Additions
* Subtraction
* Mutliplication
* Division
* Matrix Multiplication

In [14]:
sample_tensor = torch.tensor([1,2,3,4])

print("Tensor : ",sample_tensor)

# addition - torch.add()
print("Addition : ",sample_tensor + 10)

# subtraction
print("Subtraction : ",sample_tensor - 10)

# multiplication
print("Multiplication : ",sample_tensor * 10)

# division
print("Division : ",sample_tensor / 10)

# multiplication of two tensors
sample_tensor * sample_tensor

Tensor :  tensor([1, 2, 3, 4])
Addition :  tensor([11, 12, 13, 14])
Subtraction :  tensor([-9, -8, -7, -6])
Multiplication :  tensor([10, 20, 30, 40])
Division :  tensor([0.1000, 0.2000, 0.3000, 0.4000])


tensor([ 1,  4,  9, 16])

### Matrix Multiplication

In [15]:
# torch.matmul(tensor,tensor)

# Rules
# Matrix 1 = (row 1, column 1)
# Matrix 2 = (row 2, column 2)
# 1. column 1 == row 2

tensor_1 = torch.rand(size=(3,2))
tensor_2 = torch.rand(size=(2,3))
tensor_3 = torch.matmul(tensor_1,tensor_2)

print(tensor_1,"\n*\n",tensor_2,"\n=\n",tensor_3)

tensor([[0.8680, 0.3678],
        [0.4549, 0.9076],
        [0.4681, 0.9495]]) 
*
 tensor([[0.4133, 0.8495, 0.7520],
        [0.6083, 0.5633, 0.9606]]) 
=
 tensor([[0.5825, 0.9445, 1.0061],
        [0.7401, 0.8976, 1.2139],
        [0.7710, 0.9325, 1.2641]])


## Mistakes

In [16]:
# breaking the rule of matrix multiplication
# solution is to transpose the matrix
print("Transpose of the tensor 1 : \n",tensor_1.T)
print("Transpose of the tensor 2 : \n",tensor_2.T)

Transpose of the tensor 1 : 
 tensor([[0.8680, 0.4549, 0.4681],
        [0.3678, 0.9076, 0.9495]])
Transpose of the tensor 2 : 
 tensor([[0.4133, 0.6083],
        [0.8495, 0.5633],
        [0.7520, 0.9606]])


## Aggregation functions

In [17]:
# min
print("Minimum  : ",tensor_1.min())

# max
print("Maximum : ",tensor_2.max())

# mean - it won't work without the float datatype
print("Mean : ",tensor_2.mean())

# sum
print("Sum : ",tensor_2.sum())

Minimum  :  tensor(0.3678)
Maximum :  tensor(0.9606)
Mean :  tensor(0.6912)
Sum :  tensor(4.1470)


In [18]:
sample_tensor = torch.arange(start = 0 , end = 10,step = 2)
print(sample_tensor)
# argmax() - to return the position of maximum value
print("The maximum position : ",sample_tensor.argmax())
print("To remove the tensor() : ",sample_tensor.argmax().item())
# argmin() - to return the minimum value's position
print("The minimum position : ",sample_tensor.argmin())

tensor([0, 2, 4, 6, 8])
The maximum position :  tensor(4)
To remove the tensor() :  4
The minimum position :  tensor(0)


## Changing the data type

In [19]:
float_tensor = torch.arange(start = 0,end = 100,step = 10,dtype=torch.float64)
print("The float data type of tensor : ",float_tensor.dtype)

int_tensor = float_tensor.type(torch.int8)
print("The int data type of tensor : ",int_tensor)

The float data type of tensor :  torch.float64
The int data type of tensor :  tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)


## Reshape , Squeeze , Unsqueeze , Stacking

In [20]:
tensor = torch.arange(1.,11.)
print("The tensor : \n",tensor)
print("The shape of the tensor :\n",tensor.shape)

# Adding a new dimension by reshaping
print("\nThe added dimension : \n",tensor.reshape(1,10))

# view
print("\nThe view of tensor : \n",tensor.view(2,5))
# if a value is changed in view then the value in the tensor also changed

# stack
# dim = 0 for stacking vertically
#   tensor 1
#   tensor 2
#   tensor 3
# dim = 1 for stacking horizontally
#   tensor 1 tensor 2 tensor 3
print("\nThe stack of vertical tensor : \n",torch.stack([tensor,tensor,tensor],dim=0))
print("The stack of horizontal tensor : \n",torch.stack([tensor,tensor,tensor],dim=1))

# squeezing
reshaped_tensor = tensor.reshape(1,10)
print("\nReshaped Tensor : ",reshaped_tensor.shape)
squeezed_tensor = tensor.squeeze()
print("Squeezed tensor : ",squeezed_tensor.shape)
unsqueezed_tensor = tensor.unsqueeze(dim=0)
print("Unsqueezed tensor : ",unsqueezed_tensor.shape)

# permutation
unpermutated = torch.rand(size = (3,244,244))
# 2 is 244 , 0 is 3 and 1 is 224
permutated = unpermutated.permute(2,0,1)
print("\nUnpermutated : ",unpermutated.shape)
print("Permutated : ",permutated.shape)

The tensor : 
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
The shape of the tensor :
 torch.Size([10])

The added dimension : 
 tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

The view of tensor : 
 tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

The stack of vertical tensor : 
 tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
The stack of horizontal tensor : 
 tensor([[ 1.,  1.,  1.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [10., 10., 10.]])

Reshaped Tensor :  torch.Size([1, 10])
Squeezed tensor :  torch.Size([10])
Unsqueezed tensor :  torch.Size([1, 10])

Unpermutated :  torch.Size([3, 244, 244])
Permutated :  torch.Size([244, 3, 244])


## Indexing

In [21]:
tensor = torch.arange(1,10).reshape(1,3,3)
print(tensor,tensor.shape)

print("Part 1 :\n",tensor[0])
print("Part 2 :\n",tensor[0][0])
print("Part 3 :\n",tensor[0][0][0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
Part 1 :
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Part 2 :
 tensor([1, 2, 3])
Part 3 :
 tensor(1)


## Numpy and Tensor

In [22]:
from numpy import arange

# from numpy to array
array = arange(1.,10.)
print(array)
tensor = torch.from_numpy(array)
print(tensor)

# from tensor to numpy
numpy_array = tensor.numpy()
print(numpy_array,numpy_array.dtype)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
[1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


## Random Seed

In [23]:
random_seeds = 42
torch.manual_seed(seed = random_seeds)
tensor1 = torch.rand(3,3)

# resetting the seed for randomness
torch.random.manual_seed(seed = random_seeds)
tensor2 = torch.rand(3,3)

tensor1 == tensor2

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## GPU

In [24]:
# check for gpu
torch.cuda.is_available()

True

In [25]:
# setting the device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [26]:
# number of device pytorch uses
torch.cuda.device_count()

1

In [27]:
# tensor to gpu
print(tensor,tensor.device)
tensor_gpu = tensor.to(device)
print(tensor_gpu.device)

# if tensor is on gpu then it can't be converted to numpy
tensor_cpu = tensor_gpu.cpu()
print(tensor_cpu.device)


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64) cpu
cuda:0
cpu


## Exercise

In [28]:
# 2
random_tensor = torch.rand(size=(7,7))
print(random_tensor,random_tensor.shape,random_tensor.dtype)

tensor([[0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274, 0.2696, 0.4414, 0.2969],
        [0.8317, 0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090, 0.5779],
        [0.9040, 0.5547, 0.3423, 0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895, 0.7539, 0.1952, 0.0050],
        [0.3068, 0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913]]) torch.Size([7, 7]) torch.float32


In [29]:
# 3 matrix multiplication
random_tensor2 = torch.rand(size=(1,7))
print(random_tensor2)

print("Matrix multiplication : \n",torch.matmul(random_tensor,random_tensor2.T))

tensor([[0.8913, 0.1447, 0.5315, 0.1587, 0.6542, 0.3278, 0.6532]])
Matrix multiplication : 
 tensor([[1.6023],
        [1.6286],
        [1.2705],
        [2.2861],
        [2.2581],
        [1.8172],
        [1.8756]])


In [30]:
# 4
random_seed = 0
torch.manual_seed(seed = random_seed)
random_tensor = torch.rand(size=(7,7))
print(random_tensor)
torch.random.manual_seed(seed = random_seed)
random_tensor2 = torch.rand(size=(1,7))
print(random_tensor2)

print("Matrix multiplication : \n",torch.matmul(random_tensor,random_tensor2.T))

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
Matrix multiplication : 
 tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


In [48]:
# 5
random_seed = 1234
torch.cuda.manual_seed(random_seed)

In [32]:
# 6
torch.manual_seed(random_seed)
tensor1_cpu = torch.rand(2,3)
tensor2_cpu = torch.rand(2,3)
# to gpu
tensor1_gpu = tensor1_cpu.to(device)
tensor2_gpu = tensor2_cpu.to(device)

In [33]:
# 7
tensor_mm = torch.matmul(tensor1_gpu,tensor2_gpu.T)

In [34]:
# 8
print("Maximum : ",tensor_mm.max())
print("Minimum : ",tensor_mm.min())

Maximum :  tensor(0.5617, device='cuda:0')
Minimum :  tensor(0.3647, device='cuda:0')


In [35]:
# 9
print("Max position : ",tensor_mm.argmax())
print("Min position : ",tensor_mm.argmin())

Max position :  tensor(3, device='cuda:0')
Min position :  tensor(0, device='cuda:0')


In [49]:
# 10
random_seed = 7
torch.manual_seed(random_seed)
rand_tensor = torch.rand(size=(1,1,1,10))
rand_tensor2 = rand_tensor.squeeze()
rand_tensor,rand_tensor.shape,rand_tensor2,rand_tensor2.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))